server.port=8085
spring.application.name=gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Methods Access-Control-Allow-Headers, RETAIN_FIRST

spring.cloud.gateway.routes[0].id=conta-service-contas
spring.cloud.gateway.routes[0].uri=lb://conta-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/contas-banco/**

spring.cloud.gateway.routes[1].id=conta-service-auth
spring.cloud.gateway.routes[1].uri=lb://conta-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/login,/clientes/**

spring.cloud.gateway.routes[2].id=transferencia-service-route
spring.cloud.gateway.routes[2].uri=lb://transferencia-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/transferencias/**
